Added Dimonds and Ownership to cli and refactored subparser[Issue #20]
G7DAO/contracts pull request #21
Opened 2023-01-18 07:26 UTC by muddi900

Fixes #20

2023-01-18 23:10 UTC, zomglings commented on game7ctl/game7ctl/cli.py
> +def add_subparser(cmd_name: str, subparser, cli_gen: callable):
@muddi900 : Seems like an unnecesary abstraction - you aren't really saving anything with this `add_subparser` function.

But if you do want to keep it, I don't have a super strong opinion.

I would suggest:
1. `subparser` should have type annotation: `argparse.ArgumentParser`
2. Fix type annotation on `cli_gen` using `typing.Callable` - https://mypy.readthedocs.io/en/stable/kinds_of_types.html#callable-types-and-lambdas

2023-01-20 17:20 UTC, zomglings commented
@muddi900 : Looks ok to me, could you please bump the version to 0.0.2?

2023-01-20 17:51 UTC, zomglings commented
@muddi900 : Could you merge `main`, as well? And run `black` on your code?

2023-01-23 07:04 UTC, muddi900 commented
The branch is rebased, the code is reformatted and the version number is bumped.

2023-01-28 20:08 UTC, ogarciarevett requested changes
Please aim to the  "develop" branch

2023-01-30 05:59 UTC, zomglings approved these changes
lgtm

@ogarciarevett : I changed target branch to `develop` myself. Merging now.

2023-01-30 06:00 UTC, merged